package com.example.domain.model

data class HourItemDomain(
    val feelslikeC: Double? = null,
    val feelslikeF: Double? = null,
    val windDegree: Int? = null,
    val windchillF: Double? = null,
    val windchillC: Double? = null,
    val tempC: Double? = null,
    val tempF: Double? = null,
    val cloud: Int? = null,
    val windKph: Double? = null,
    val windMph: Double? = null,
    val snowCm: Int? = null,
    val humidity: Int? = null,
    val dewpointF: Int? = null,
    val willItRain: Int? = null,
    val uv: Int? = null,
    val heatindexF: Double? = null,
    val dewpointC: Double? = null,
    val isDay: Int? = null,
    val precipIn: Int? = null,
    val heatindexC: Double? = null,
    val windDir: String? = null,
    val gustMph: Double? = null,
    val pressureIn: Double? = null,
    val chanceOfRain: Int? = null,
    val gustKph: Double? = null,
    val precipMm: Double? = null,
    val condition: ConditionDomain? = null,
    val willItSnow: Int? = null,
    val visKm: Int? = null,
    val timeEpoch: Int? = null,
    val time: String? = null,
    val chanceOfSnow: Int? = null,
    val pressureMb: Int? = null,
    val visMiles: Int? = null
)