package com.example.domain.model

data class HourItemDomain(
    val feelslikeC: Double? = null,
    val feelslikeF: Double? = null,
    val windDegree: Double? = null,
    val windchillF: Double? = null,
    val windchillC: Double? = null,
    val tempC: Double? = null,
    val tempF: Double? = null,
    val cloud: Double? = null,
    val windKph: Double? = null,
    val windMph: Double? = null,
    val snowCm: Double? = null,
    val humidity: Double? = null,
    val dewpointF: Double? = null,
    val willItRain: Int? = null,
    val uv: Double? = null,
    val heatindexF: Double? = null,
    val dewpointC: Double? = null,
    val isDay: Int? = null,
    val precipIn: Double? = null,
    val heatindexC: Double? = null,
    val windDir: String? = null,
    val gustMph: Double? = null,
    val pressureIn: Double? = null,
    val chanceOfRain: Double? = null,
    val gustKph: Double? = null,
    val precipMm: Double? = null,
    val condition: ConditionDomain? = null,
    val willItSnow: Int? = null,
    val visKm: Double? = null,
    val timeEpoch: Int? = null,
    val time: String? = null,
    val chanceOfSnow: Double? = null,
    val pressureMb: Double? = null,
    val visMiles: Double? = null
)